# Generated by Django 3.1 on 2020-08-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('point', models.IntegerField(default=0)),
                ('purchase_count', models.IntegerField(default=0)),
                ('purchase_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sell_total', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('recent_login', models.DateTimeField(auto_now=True, null=True)),
                ('sleep_expiration_date', models.DateTimeField(auto_now=True, null=True)),
                ('is_approved', models.BooleanField(default=True)),
                ('coupon', models.CharField(default=0, max_length=50)),
                ('gender', models.CharField(max_length=50)),
                ('bank_account', models.CharField(blank=True, max_length=160)),
                ('social_login_id', models.CharField(blank=True, max_length=50)),
                ('login_fail_count', models.IntegerField(blank=True, default=0)),
                ('is_lock', models.BooleanField(default=False)),
                ('latest_try_login_date', models.DateTimeField(default=None, null=True)),
                ('lock_count', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_deleted', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
