# Generated by Django 3.1 on 2020-08-28 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200828_0539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialplatform',
            name='platform',
            field=models.CharField(max_length=20),
        ),
    ]
